<?php

/**
 * @file
 * Primary hook implementations.
 */

/**
 * Implements hook_menu().
 */
function islandora_datastream_filenamer_menu() {
  $items['admin/islandora/tools/islandora_datastream_filenamer'] = array(
    'title' => 'Islandora Datastream Filenamer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_datastream_filenamer_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_token_info().
 *
 * Contains the 'fedora' tokens that are part of islandora_pathauto.
 */
function islandora_datastream_filenamer_token_info() {
  return array(
    'types' => array(
      'dsfilename' => array(
        'name' => 'Datastream tokens',
        'description' => t("Tokens for islandora relating to datastreams objects.")
      ),
    ),
    'tokens' => array(
      'dsfilename' => array(
        'fileextension' => array(
          'name' => t("Extension from Datastream's Mimetype"),
          'description' => t("File extension derived from mimetype.")
        ),
        'id' => array(
          'name' => t("Datastream's ID"),
          'description' => t('Datastream ID.')
        ),
        'label' => array(
          'name' => t("Datastream's label"),
          'description' => t("Datastream label.")
        ),
      ),
    ),
  );
}

/**
 * Implements hook_tokens().
 */
function islandora_datastream_filenamer_tokens($type, $tokens, array $data = array(), array $options = array()) {
  if ($type == 'dsfilename' && is_object($data['datastream'])) {
    $datastream = $data['datastream'];
    $replacements = array();
    foreach ($tokens as $name => $original) {
      if ($datastream) {
        if ($name == 'fileextension') {
          $replacements[$original] = islandora_get_extension_for_mimetype($datastream->mimetype);
        }
        if ($name == 'id') {
          $replacements[$original] = $datastream->id;
        }
        if ($name == 'label') {
          $replacements[$original] = $datastream->label;
        }
      }
    }
    return $replacements;
  }
  return array();
}

function islandora_datastream_filenamer_create_datastream_filename($datastream) {
  $filename = token_replace(variable_get('islandora_ds_download_filename_pattern'),
    array(
      'datastream' => $datastream,
      'fedora' => $datastream->parent,
    ),
    array(
      'clear' => TRUE,
    )
  );

  // Decode any entities.
  $filename = decode_entities($filename);

  return $filename;
}

/**
 * Implements hook_islandora_datastream_filename_alter().
 */
function islandora_datastream_filenamer_islandora_datastream_filename_alter(&$filename, AbstractDatastream $datastream) {
  $filename = islandora_datastream_filenamer_create_datastream_filename($datastream);
}
